# Generated by Django 4.2.3 on 2023-07-30 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sampleApp', '0007_bookissue'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(default='covers/profile/user.png', upload_to='covers/profile'),
        ),
    ]
